# NumPy tutorial

[Numerical Python](https://numpy.org) is one of the most fundamental tools in each data miner's toolbox. It is impossible to do serious data pre-processing and transformation without the understanding of `NumPy` and its most commonly used methods. The goal of this tutorial is to familiarize students with this awesome library.

## Introduction

99% of `NumPy` is one data structure and operations on that structure. `NumPy` stores everything in multidimensional arrays and vectorizes all operations on these arrays. For a motivating example, let's compare the speed of computing an average of 10 mln of random numbers stored in a list vs an array

In [1]:
import numpy as np
from numpy.random import randint

randoms = randint(low=0, high=1000, size=100000000)
lst = list(randoms)

In [2]:
len(lst)

100000000

In [3]:
%%time

# old-school iteration
summ = 0
for i in range(len(lst)):
    summ += lst[i]
    
print(f'Average = {summ/len(lst)}')

<timed exec>:4: RuntimeWarning: overflow encountered in long_scalars


Average = -15.96283896
CPU times: total: 22.3 s
Wall time: 22.3 s


In [4]:
%%time

# using built-ins sum() and len()
print(f'Average = {sum(lst)/len(lst)}')

Average = -15.96283896
CPU times: total: 4.05 s
Wall time: 4.06 s


<timed eval>:2: RuntimeWarning: overflow encountered in long_scalars


In [5]:
%%time

# using NumPy
print(f'Average = {np.mean(randoms)}')

Average = 499.43323656
CPU times: total: 219 ms
Wall time: 220 ms


There are only two rules regarding `NumPy` arrays:
- every element must be of the same type and size
- if an array has arrays, they must match as well

Let's see how to create an array and what happens when we start messing with the types and sizes of objects

In [10]:
a = np.array([1, 2, 3, 4, 5], dtype=np.int16)

print(f'Shape (sizes of dimensions): {a.shape}')
print(f'Number of dimensions: {a.ndim}')
print(f'Length (number of elements): {len(a)}')
print(f'Size (number of nested elements): {a.size}')
print(f'Type : {type(a)}')
print(f'Data type (type of array elements): {a.dtype}')

Shape (sizes of dimensions): (5,)
Number of dimensions: 1
Length (number of elements): 5
Size (number of nested elements): 5
Type : <class 'numpy.ndarray'>
Data type (type of array elements): int16


Now let's see how the same descriptors can be applied to a two-dimensional array

In [7]:
a = np.array([
    [1, 2, 3, 4, 5],
    [1, 4, 9, 16, 25]
], dtype=np.int16)

print(f'Shape (sizes of dimensions): {a.shape}')
print(f'Number of dimensions: {a.ndim}')
print(f'Length (number of elements): {len(a)}')
print(f'Size (number of nested elements): {a.size}')
print(f'Type : {type(a)}')
print(f'Data type (type of array elements): {a.dtype}')

Shape (sizes of dimensions): (2, 5)
Number of dimensions: 2
Length (number of elements): 2
Size (number of nested elements): 10
Type : <class 'numpy.ndarray'>
Data type (type of array elements): int16


Array elements should be of the same type. Let's see what happens if we mix two types.

In [14]:
a = np.array([1, 2, 'mary', 'had', 2, 'lambs', True])

a

array(['1', '2', 'mary', 'had', '2', 'lambs', 'True'], dtype='<U11')

In [12]:
a.dtype

dtype('<U11')

We can also try to modify the length of array's elements

In [15]:
a = np.array(['mary', 'had', 'a', 'little', 'lamb'])

In [16]:
a.dtype, a

(dtype('<U6'), array(['mary', 'had', 'a', 'little', 'lamb'], dtype='<U6'))

In [17]:
a[4] = 'and very very very very long snake'

print(a)

['mary' 'had' 'a' 'little' 'and ve']


After an array has been created, it can be reshaped to whatever shape one desires. A special function is provided for transposing an array (changing rows into columns and vice versa)

In [18]:
a = np.array([0,1,2,3,4,5,6,7,8,9,10,11])

In [19]:
a.shape

(12,)

In [20]:
a.shape = (1, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [21]:
??np.reshape

In [22]:
a = a.reshape(3, 4)

a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
# transposition of an arary

a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## Creating arrays

The easiest way to create a 1-d array is to use a list. If you want a 2-d array, you use a list of lists. 3-d arrays are created using a list of lists of lists. You get the gist.

In [24]:
a_1d = np.array([1, 2, 3, 4])

a_2d = np.array([
    [1, 2, 3, 4],
    [1, 4, 9, 16],
    [1, 8, 27, 64]
])

a_3d = np.array([
    [
        [0, 0],
        [0, 1],
    ],
    [
        [1, 0],
        [1, 1],
    ],
])

In [25]:
a_2d

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16],
       [ 1,  8, 27, 64]])

There are utility functions in the `np` module for creating popular types of arrays:
- an array filled with zeros
- an array filled with ones
- an array filled with any value
- an array of consecutive (or stepped) values
- an array filled with random values
- a diagonal array

In [26]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.zeros(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((3,2,3), dtype=np.int16)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [29]:
np.full(shape=(4,2), fill_value='mary had a little lamb')

array([['mary had a little lamb', 'mary had a little lamb'],
       ['mary had a little lamb', 'mary had a little lamb'],
       ['mary had a little lamb', 'mary had a little lamb'],
       ['mary had a little lamb', 'mary had a little lamb']], dtype='<U22')

In [30]:
??np.arange

In [31]:
np.arange(-2, 2, 0.5)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5])

In [50]:
??np.random.randn

In [38]:
np.random.randn(3, 3)

array([[ 0.53973741, -0.3735185 , -0.39368492],
       [-0.96229312, -0.21763466, -0.2270881 ],
       [-1.25246395, -1.83097599,  1.21328249]])

In [49]:
np.random.randint(low=1, high=7, size=(3,3))

array([[1, 6, 4],
       [3, 6, 6],
       [2, 6, 6]])

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(5, 8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

## Indexing arrays

Arrays in `NumPy` are 0-indexed. Indexing of 1-d arrays is very easy, just follow the pattern of *start*:*end*:*step*

In [51]:
a = np.arange(0, 10)

print(f'Full array: {a}')
print(f'First element: {a[0]}')
print(f'First three elements: {a[0:3]}')
print(f'Last element: {a[len(a)-1]} and {a[-1]}')
print(f'Even elements: {a[::2]}')

Full array: [0 1 2 3 4 5 6 7 8 9]
First element: 0
First three elements: [0 1 2]
Last element: 9 and 9
Even elements: [0 2 4 6 8]


Indexing of n-dim arrays is a bit more tricky. Keep in mind that axis 0 refers to rows and axis 1 refers to columns. For high dimensional arrays try to build the following intuition:
- 1-d: a row of values
- 2-d: a matrix (rows and columns) of values
- 3-d: a row of arrays
- 4-d: a matrix of arrays
- and so on...

In [52]:
a = np.array([
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [100, 200, 300, 400],
])

print(a)

print(f'Element at second row, third column: {a[1,2]}')
print(f'Entire first row: {a[0,]}')
print(f'Entire first row as 2-d array: {a[0, None]}')
print(f'First and second rows, last column: {a[:2,-1]}')


[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]]
Element at second row, third column: 30
Entire first row: [1 2 3 4]
Entire first row as 2-d array: [[1 2 3 4]]
First and second rows, last column: [ 4 40]


The same goes with all n-dim arrays. For instance, let's extract first matrix, all rows, first column. You can also use indexing to assign multiple values to array cell at once.

In [53]:
a_3d

array([[[0, 0],
        [0, 1]],

       [[1, 0],
        [1, 1]]])

In [54]:
a_3d[1, :, 0]

array([1, 1])

In [59]:
a_3d[1, :, 1] = -1

print(a_3d)

[[[ 0  0]
  [ 0  1]]

 [[-1 -1]
  [-1 -1]]]


## Basic operations on arrays

All array operations are vectorized, so they tend to be very quick. By default, `NumPy` performs element-wise array operations. If you want to correctly multiply arrays, use `@` operator as shown below.

In [60]:
a = np.arange(0, 12)
b = np.arange(12, 24)

a.shape = b.shape = 3, 4

In [61]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
a + b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [64]:
b - a

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [65]:
a + 10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [66]:
a.shape, b.shape

((3, 4), (3, 4))

In [67]:
a @ b.T 

array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

## Exercises

### Calculating sliding averages

Given an array of daily measurements, create a new array with averages computed over each pair of consecutive days

In [68]:
measurements = np.arange(100)
...

In [69]:
measurements

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [104]:
print(measurements[:-1])
print(measurements[1:])

(measurements[:-1] + measurements[1:]) / 2

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
       11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5,
       22.5, 23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5,
       33.5, 34.5, 35.5, 36.5, 37.5, 38.5, 39.5, 40.5, 41.5, 42.5, 43.5,
       44.5, 45.5, 46.5, 47.5, 48.5, 49.5, 50.5, 51.5, 52.5, 53.5, 54.5,
       55.5, 56.5, 57.5, 58.5, 59.5, 60.5, 61.5, 62.5, 63.5, 64.5, 65.5,
       66.5, 67.5, 68.5, 69.5, 70.5, 71.5, 72.5, 73.5, 74.5, 75.5, 76.5,
       77.5, 78.5, 79.5, 80.5, 81.5, 82.5, 83.5, 84.5, 85.5, 86.5, 87.5,
       88.5, 89.5, 90.5, 91.5, 92.5, 93.5, 94.5, 95.5, 96.5, 97.5, 98.5])

### Battleships

Given a 10x10 playing field with hidden battleships and a list of shooting targets, compute the number of hits.

In [100]:
sea = np.random.randint(low=0, high=2, size=(10,10))
 
sea

array([[1, 0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
       [1, 0, 0, 1, 1, 0, 1, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 0, 1, 1, 1, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 0, 1, 1, 1, 1, 1, 1, 1]])

In [101]:
targets = np.array([
    [0,3],
    [1,7],
    [2,2],
    [3,5],
    [8,2]
])
...

Ellipsis

In [103]:
print(targets[:, 0])
print(targets[:, 1])
print(sea[targets[:, 0], targets[:, 1]])

sea[targets[:, 0], targets[:, 1]].sum()

[0 1 2 3 8]
[3 7 2 5 2]
[0 0 0 1 1]


2

## Broadcasting

This is by far the most important concept in `NumPy`. Broadcasting is an automatic expansion of arrays so that they match with their operands.

Let's start with the simplest example.

In [105]:
a = np.arange(10)

a + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

The same happens for 2-d arrays

In [106]:
a = np.array([
    [1, 2, 3, 4],
    [1, 4, 9, 16],
])

b = np.array([
    [0.1, 0.2]]
)

In [107]:
a.shape, b.T.shape

((2, 4), (2, 1))

In [108]:
a + b.T

array([[ 1.1,  2.1,  3.1,  4.1],
       [ 1.2,  4.2,  9.2, 16.2]])

The simple rule for broadcasting is the following:

If we want to operate on two arrays `a` and `b`:
- moving backwards from the last dimension of each array, we check if their dimensions are the same or one equals 1
- if all of `a`'s dimensions are compatible with `b`'s dimensions, arrays `a` and `b` are compatible.

In [109]:
np.random.seed(1234)

a = np.random.randint(low = 1, high = 10, size = (3, 4))
print(a)

b = np.random.randint(low = 1, high = 10, size = (3, 1))
print(b)

[[4 7 6 5]
 [9 2 8 7]
 [9 1 6 1]]
[[7]
 [3]
 [1]]


In [110]:
a + b

array([[11, 14, 13, 12],
       [12,  5, 11, 10],
       [10,  2,  7,  2]])

In [111]:
np.random.seed(1234)

a = np.random.randint(low = 1, high = 10, size = (3, 1, 4))
print(a)

b = np.random.randint(low = 1, high = 10, size = (2, 1))
print(b)

[[[4 7 6 5]]

 [[9 2 8 7]]

 [[9 1 6 1]]]
[[7]
 [3]]


In [112]:
(a + b).shape

(3, 2, 4)

In [113]:
a + b

array([[[11, 14, 13, 12],
        [ 7, 10,  9,  8]],

       [[16,  9, 15, 14],
        [12,  5, 11, 10]],

       [[16,  8, 13,  8],
        [12,  4,  9,  4]]])

Sometimes it is useful to be able to manually modify the shape of the array. This can be done using the `np.newaxis` function (which is simply an alias for the `None` keyword)

In [114]:
a = np.array([1, 2, 3, 5, 7, 11, 13])

In [115]:
a.shape

(7,)

In [121]:
a[:, np.newaxis].shape

(7, 1)

In [120]:
a[None, :].shape

(1, 7)

This can be very useful if one wants to build an array containing the results of a cross-join operation on two matrices. Suppose we are trying to create $c_{ij} = a_i - b_j$.

In [122]:
b = np.arange(7)

c = a[:, None] - b[None, :]

print(c)

[[ 1  0 -1 -2 -3 -4 -5]
 [ 2  1  0 -1 -2 -3 -4]
 [ 3  2  1  0 -1 -2 -3]
 [ 5  4  3  2  1  0 -1]
 [ 7  6  5  4  3  2  1]
 [11 10  9  8  7  6  5]
 [13 12 11 10  9  8  7]]


## Boolean indexing

Anytime you have a boolean array, you can use it to mask entries in another array.

In [123]:
a = np.random.randint(0, 100, size=(5,5))

a

array([[76, 37, 34, 38, 67],
       [11,  0, 75, 80,  3],
       [ 2, 19, 12, 65, 75],
       [81, 14, 71, 60, 46],
       [28, 81, 87, 13, 96]])

In [130]:
temps_greater_than_50 = a > 50

In [131]:
a[temps_greater_than_50]

array([76, 67, 75, 80, 65, 75, 81, 71, 60, 81, 87, 96])

Boolean masking may be applied not only to values, but to rows and columns as well. Just remember to use slicing:

*array*[*row_mask*,*col_mask*]

In [135]:
a

array([[76, 37, 34, 38, 67],
       [11,  0, 75, 80,  3],
       [ 2, 19, 12, 65, 75],
       [81, 14, 71, 60, 46],
       [28, 81, 87, 13, 96]])

In [132]:
rows_2_and_4 = np.array([False, True, False, True, False])
cols_1_and_2 = np.array([True, True, False, False, False])

In [133]:
a[rows_2_and_4]

array([[11,  0, 75, 80,  3],
       [81, 14, 71, 60, 46]])

In [134]:
a[rows_2_and_4, cols_1_and_2]

array([11, 14])

In [136]:
names = np.array(["Dennis", "Dee", "Charlie", "Mac", "Frank"])
ages = np.array([43, 44, 43, 42, 74])
genders = np.array(['male', 'female', 'male', 'male', 'male'])

In [140]:
names[(genders == 'male') & (ages > 43)]

array(['Frank'], dtype='<U7')

In [144]:
names[~(genders == 'male') & (ages % 2 == 0)]

array(['Dee'], dtype='<U7')

## `Random` module

One of the most frequently used parts of the `NumPy` is the random number generation procedure. Below you can see examples of different samples:
- normal sample
- uniform sample
- choosing from a set with/without replacement

In [145]:
np.random.normal(loc=10.0, scale=1.0, size=(3,3))

array([[ 7.77254312,  9.32518006, 11.01484933],
       [ 9.44297546,  9.57539397, 10.13749589],
       [ 9.92948695, 10.32539432,  9.52647845]])

In [146]:
np.random.randint(low=10, high=20, size=(3,3))

array([[12, 15, 16],
       [17, 14, 13],
       [15, 16, 14]])

In [147]:
np.random.uniform(low=0, high=1, size=5)

array([0.32815036, 0.47386   , 0.06808472, 0.3827107 , 0.11855414])

In [148]:
np.random.choice(
    a=[1,2,3,4,5,6],
    replace=True,
    size=10
)

array([4, 3, 2, 5, 2, 1, 2, 3, 2, 3])

In [149]:
np.random.choice(
    a=['this','is','sampling','without','replacement'],
    replace=True,
    size=8
)

array(['is', 'sampling', 'is', 'is', 'replacement', 'is', 'sampling',
       'replacement'], dtype='<U11')

Despite the fact that most people use the `random` module as above, this way is in fact deprecated, because it introduces a dependency on the random number generator used currently by `NumPy`. In theory, if `NumPy` changes the generator, all the code becomes non-reproducible.
A simple solution is to use the generic `Generator` class.

In [150]:
generator = np.random.default_rng(seed=123)

In [151]:
generator.integers(low=1, high=100, size=10)

array([ 2, 68, 59,  6, 90, 22, 26, 19, 34, 18], dtype=int64)

In [152]:
generator.normal(loc=0, scale=1, size=10)

array([ 0.57710379, -0.63646365,  0.54195222, -0.31659545, -0.32238912,
        0.09716732, -1.52593041,  1.1921661 , -0.67108968,  1.00026942])

In [153]:
generator.choice(a=[1,2,3], replace=True, size=10)

array([1, 2, 2, 3, 3, 1, 3, 3, 1, 2])

## Exercises

### Two reviewers

You are given two arrays representing ratings assigned to 100 movies by two reviewers. Identify movies such that the reviewers differ in their rating by at most 1.

In [154]:
movies = np.arange(100)
reviewer_a = np.random.choice(a=[1,2,3,4,5], size=100)
reviewer_b = np.random.choice(a=[1,2,3,4,5], size=100)

In [158]:
print("movies", movies)
print("reviewer a:", reviewer_a)
print("reviewer a:", reviewer_b)

movies [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
reviewer a: [1 5 2 3 2 2 4 5 2 4 3 1 5 4 5 1 1 5 1 5 2 1 2 1 3 1 4 3 3 4 3 2 5 1 2 2 3
 3 5 4 3 5 2 1 1 4 5 1 1 2 1 4 2 2 2 4 4 2 4 5 5 5 2 4 2 3 2 1 1 5 5 1 1 2
 4 2 5 2 4 3 4 3 3 1 2 2 4 4 5 4 3 5 3 2 4 3 1 2 2 4]
reviewer a: [5 4 5 3 4 2 1 1 1 2 3 4 2 5 4 2 1 2 5 3 4 2 3 2 5 4 1 5 4 5 1 1 1 2 4 5 1
 2 2 1 5 2 2 2 3 4 5 3 4 2 2 5 1 1 3 2 5 3 4 3 2 1 1 3 1 1 2 2 5 4 3 1 1 3
 1 5 1 4 3 5 5 3 4 5 3 1 3 2 2 1 1 1 2 5 3 2 2 5 2 2]


In [214]:
reviews_num = reviewer_a - reviewer_b
reviews_num = np.abs(reviews_num)
movies[(reviews_num <= 1)]


array([ 1,  3,  5,  8, 10, 13, 14, 15, 16, 21, 22, 23, 28, 29, 31, 33, 37,
       42, 43, 45, 46, 49, 50, 51, 52, 53, 54, 56, 57, 58, 62, 63, 64, 66,
       67, 69, 71, 72, 73, 78, 80, 81, 82, 84, 85, 86, 92, 94, 95, 96, 98])

In [197]:
movies[np.abs(reviewer_a - reviewer_b) <= 1]

array([ 1,  3,  5,  8, 10, 13, 14, 15, 16, 21, 22, 23, 28, 29, 31, 33, 37,
       42, 43, 45, 46, 49, 50, 51, 52, 53, 54, 56, 57, 58, 62, 63, 64, 66,
       67, 69, 71, 72, 73, 78, 80, 81, 82, 84, 85, 86, 92, 94, 95, 96, 98])

## Using `where`

`np.where` is a very useful function which allows to quickly filter elements of an array based on the condition. Imagine you have two large arrays and you want to create a third array such that it contains, for each cell, the larger value from the two arrays. First, let's do it in a traditional way.

In [5]:
a = np.random.randint(1, 6, size=10**6)
b = np.random.randint(1, 6, size=10**6)

In [9]:
a

array([2, 3, 3, ..., 4, 2, 5])

In [10]:
b

array([2, 5, 1, ..., 4, 1, 3])

In [6]:
%%time
c = np.zeros(a.size)

for i in range(a.size):
    if a[i] > b[i]:
        c[i] = a[i]
    else:
        c[i] = b[i]


CPU times: total: 375 ms
Wall time: 385 ms


In [7]:
%%time
d = np.where(a > b, a, b)

CPU times: total: 0 ns
Wall time: 8.45 ms


In [8]:
d

array([2, 5, 3, ..., 4, 2, 5])

In [172]:
np.array_equal(c,d)

True

## Exercises

### First to finish the assignment

Given an array with students' assignments ordered by the increasing date of submission, you want to reward first 3 students who submitted their work and who got at least 75 points. Increase their scores by 5 points.

In [31]:
grades = np.random.randint(low=0, high=100, size=50)
grades

array([27, 65, 14,  3, 53, 72, 90,  3, 73, 78, 50, 78, 53, 35, 21, 77, 87,
       72, 96,  7, 84, 92, 51, 26, 93, 42,  0, 27, 43, 18, 39, 76, 85, 59,
       38, 55, 33, 86, 65,  2, 74, 64, 93,  4, 58, 62,  5, 60, 27, 31])

In [39]:
good_grades_positions = np.where((grades > 75))[0]
print(good_grades_positions)

good_grades_fastests_positions = good_grades_positions[:3]
print(good_grades_fastests_positions)

[ 6  9 11 15 16 18 20 21 24 31 32 37 42]
[ 6  9 11]


In [45]:
extra_grades = grades
extra_grades[good_grades_fastests_positions] = extra_grades[good_grades_fastests_positions] + 5
extra_grades

array([27, 65, 14,  3, 53, 72, 95,  3, 73, 83, 50, 83, 53, 35, 21, 77, 87,
       72, 96,  7, 84, 92, 51, 26, 93, 42,  0, 27, 43, 18, 39, 76, 85, 59,
       38, 55, 33, 86, 65,  2, 74, 64, 93,  4, 58, 62,  5, 60, 27, 31])

## Math functions

`NumPy` contains several highly optimized implementations of math functions. Whenever possible, try to use them instead of your own implementations. Remember, that math functions are easily generalized to n-dim arrays.

In [174]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
], dtype=np.float64)

In [175]:
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [176]:
np.sum(a)

136.0

In [177]:
np.sum(a, axis=0)

array([28., 32., 36., 40.])

In [178]:
np.sum(a, axis=1)

array([10., 26., 42., 58.])

But beware of `nan`s, as they tend to destroy all math!

In [183]:
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [184]:
a[2,2] = np.nan

In [185]:
a.sum()

nan

In [186]:
a[~np.isnan(a)]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 12., 13., 14.,
       15., 16.])

In [187]:
a[~np.isnan(a)].sum()

125.0

In [188]:
np.sum(a, where=~np.isnan(a))

125.0

In [189]:
np.nansum(a)

125.0

In [190]:
np.sum(np.nan_to_num(a))

125.0

Let's see what else we can do with `nan`s

In [192]:
a[0,1] = np.nan
a[1,3] = np.nan

In [193]:
np.isnan(a)

array([[False,  True, False, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False, False, False]])

In [194]:
np.any(np.isnan(a), axis=1)

array([ True,  True,  True, False])

In [195]:
mask = np.any(np.isnan(a), axis=1)
a[mask]

array([[ 1., nan,  3.,  4.],
       [ 5.,  6.,  7., nan],
       [ 9., 10., nan, 12.]])

## Concatenation & sorting

Concatenation means joining two arrays by rows or by columns. An array may be concatenated with itself or with another array. There are 4 functions that help with concatenation.

In [198]:
a = np.zeros(shape=(3,2))
b = np.ones(shape=(2,2))

In [199]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [200]:
b

array([[1., 1.],
       [1., 1.]])

In [201]:
np.concatenate([a, a, a, a], axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [202]:
np.concatenate([a, b], axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [203]:
np.vstack([a,b])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [204]:
np.hstack([a.T,b])

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [205]:
np.stack([a[:2,:2], b], axis=0)

array([[[0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 1.]]])

Unfortunately, `NumPy` does not provide any easy way of reverse sort, and sorting is limited to two functions.

In [206]:
a = np.random.randint(1, 100, size=50)
a

array([59, 18, 55, 43, 94, 15, 30, 63, 32, 73, 32, 70,  4, 70, 67, 27, 89,
       40, 37, 19, 88, 47, 77, 39, 67, 26, 55,  3, 58, 56, 78, 55, 21, 24,
       65,  2,  9, 88, 21, 43,  7,  3, 47, 19, 48, 83, 17, 52, 99,  2])

In [207]:
a.sort()

In [208]:
a[::-1]

array([99, 94, 89, 88, 88, 83, 78, 77, 73, 70, 70, 67, 67, 65, 63, 59, 58,
       56, 55, 55, 55, 52, 48, 47, 47, 43, 43, 40, 39, 37, 32, 32, 30, 27,
       26, 24, 21, 21, 19, 19, 18, 17, 15,  9,  7,  4,  3,  3,  2,  2])

In [209]:
np.sort(a)[::-1]

array([99, 94, 89, 88, 88, 83, 78, 77, 73, 70, 70, 67, 67, 65, 63, 59, 58,
       56, 55, 55, 55, 52, 48, 47, 47, 43, 43, 40, 39, 37, 32, 32, 30, 27,
       26, 24, 21, 21, 19, 19, 18, 17, 15,  9,  7,  4,  3,  3,  2,  2])

If you want to be able to sort values in the first column of an array according to the order in the second column of an array, you need to use `np.argsort`.

In [210]:
a = np.random.randint(1, 100, size=20)
a.shape = 5,4

print(a)

[[89 76 36 45]
 [ 9 46 50 83]
 [29 63 81 42]
 [76 31 52 45]
 [93 22 30 77]]


In [211]:
np.sort(a, axis=0)

array([[ 9, 22, 30, 42],
       [29, 31, 36, 45],
       [76, 46, 50, 45],
       [89, 63, 52, 77],
       [93, 76, 81, 83]])

In [212]:
a

array([[89, 76, 36, 45],
       [ 9, 46, 50, 83],
       [29, 63, 81, 42],
       [76, 31, 52, 45],
       [93, 22, 30, 77]])

In [213]:
a[np.argsort(a[:,2])]

array([[93, 22, 30, 77],
       [89, 76, 36, 45],
       [ 9, 46, 50, 83],
       [76, 31, 52, 45],
       [29, 63, 81, 42]])